[Loxidation]
url="https://github.com/LevitatingBusinessMan/Loxidation.git"

[rust-coreutils]
url="https://github.com/uutils/coreutils"

[git-bro]
url="https://github.com/LevitatingBusinessMan/git-bro.git"

[solaris]
url="https://github.com/mike-eason/solaris.git"

[settings]
silent=true
