[opentrack]
url="https://github.com/opentrack/opentrack.git"

[Loxidation]
url="https://github.com/LevitatingBusinessMan/Loxidation.git"

[linux]
url="https://github.com/torvalds/linux.git"

[rust-coreutils]
url="https://github.com/uutils/coreutils"

[git-bro]
url="https://github.com/LevitatingBusinessMan/git-bro.git"

[dailyfloppa]
url="https://github.com/dev-shit/dailyfloppa.git"

[solaris]
url="https://github.com/mike-eason/solaris.git"

[settings]
silent=true
